params:
  # General
  defaultTheme: "auto" # Value: auto; light; dark;

  # .Param
  downImage:
    enable: true
    imageSpec: "fit 3200x3200"
  album:
    imageSpec:
      thumbnail: "fit 1200x1200"
  gallery:
    sort:
      - { key: "params.weight", order: "asc" }
      - { key: "params.date", order: "desc" }
      - { key: "title", order: "asc" }
      - { key: "name", order: "asc" }
    photoSwipe:
      enableCaption: true
    justified:
      gutterH: 10
      gutterV: 10
      rowHeight: 320
      rowHeightTolerance: 0.25
    imageSpec:
      thumbnail: "fit 600x600"
      lightbox: "fit 1600x1600"

  # site.Params
  imageSpec:
    rssCover: "fill 900x600"
    featured: "fit 1600x1600"
    openGraph: "fit 1600x1600"
