params:
  # General
  defaultTheme: "auto" # Value: auto; light; dark;

  # .Param
  downImage:
    enable: true
    imageSpec: "fit 3200x3200"
  album:
    imageSpec:
      thumbnail: "fit 1200x1200"
  image:
    sort:
      - { key: "params.weight", order: "asc" }
      - { key: "params.date", order: "desc" }
      - { key: "title", order: "asc" }
      - { key: "name", order: "asc" }
  gallery:
    photoSwipe:
      caption:
        enable: true
        data:
          - { format: "ISO ${Exif.ISO}", minWidth: "4rem" }
          - { format: "${Exif.FocalLengthIn35mmFormat} mm", minWidth: "4rem" }
          - { format: "${Exif.ExposureCompensation} ev", minWidth: "4rem" }
          - { format: "f ${Exif.FNumber-printf-float-%0.2f}", minWidth: "4rem" }
          - { format: "${Exif.ExposureTime} s", minWidth: "5rem" }
      fileInfo:
        enable: true
        firstBigger: true
        data:
          - { format: "${Title-title}" }
          - { format: '${SmartDate-dateFormat-2006\-01\-02 15:04:05 \-0700 MST}' }
          - { format: "${FileExt} · ${Megapixel} MP · ${Resolution} · ${FileSize-div-1048576-%0.2f} MB" }
          - { format: "${Exif.Make} ${Exif.Model}" }
    justified:
      gutterH: 10
      gutterV: 10
      rowHeight: 320
      rowHeightTolerance: 0.25
    imageSpec:
      thumbnail: "fit 600x600"
      lightbox: "fit 1600x1600"
  related:
    enable: true
    limit: 3

  # site.Params
  imageSpec:
    rssCover: "fill 900x600"
    featured: "fit 1600x1600"
    openGraph: "fit 1600x1600"
