name = "ZeroDream Gallery"
license = "MIT"
licenselink = "https://github.com/zero-dream/hugo-zero/blob/main/LICENSE"
description = "A uniquely styled Hugo photo gallery theme."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/zero-dream/hugo-zero"

# If you have a running demo of the theme.
demosite = "https://zero-dream.github.io/hugo-zero"

tags = ["zerodream", "gallery", "uniquely", "responsive", "dark"]
features = ["zerodream", "gallery", "uniquely", "responsive", "dark"]

# If the theme has a single author
[author]
    name = "ZeroDream"
    homepage = "https://github.com/zero-dream"

# If porting an existing theme
[original]
    author = "Nico Kaiser"
    homepage = "https://github.com/nicokaiser"
    repo = "https://github.com/nicokaiser/hugo-theme-gallery"
