locale: "en-us"
timeZone: "Etc/UTC"

enableRobotsTXT: true
defaultContentLanguage: "en"

baseURL: "https://example.org/"

title: "Gallery"
copyright: >
  © {{< link-blank "ZeroDream" "https://github.com/zero-dream/" >}} · 
  Powered by {{< link-blank "Hugo" "https://github.com/gohugoio/hugo/" >}} & {{< link-blank "ZeroDream" "https://github.com/zero-dream/hugo-gallery/" >}}

module:
  hugoVersion:
    extended: true
    min: "0.162.0"
  imports:
    - path: "github.com/zero-dream/hugo-gallery"

services:
  rss:
    limit: 100

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"
    - "RSS"
  page:
    - "HTML"

related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
    - weight: 100
      name: "keywords"
      type: "basic"
      applyFilter: false
      pattern: ""
      toLower: false
      cardinalityThreshold: 0
    - weight: 80
      name: "tags"
      type: "basic"
      applyFilter: false
      pattern: ""
      toLower: false
      cardinalityThreshold: 0
    - weight: 70
      name: "categories"
      type: "basic"
      applyFilter: false
      pattern: ""
      toLower: false
      cardinalityThreshold: 0
    - weight: 10
      name: "date"
      type: "basic"
      applyFilter: false
      pattern: ""
      toLower: false
      cardinalityThreshold: 0
