locale: "en-us"
timeZone: "Etc/UTC"

enableRobotsTXT: true
defaultContentLanguage: "en"

baseURL: "https://example.org/"

title: "Gallery"
copyright: >
  © {{< link-blank "ZeroDream" "https://github.com/zero-dream/" >}} · 
  Powered by {{< link-blank "Hugo" "https://github.com/gohugoio/hugo/" >}} & {{< link-blank "ZeroDream" "https://github.com/zero-dream/hugo-gallery/" >}}

module:
  hugoVersion:
    extended: true
    min: "0.162.0"
  imports:
    - path: "github.com/zero-dream/hugo-gallery"

services:
  rss:
    limit: 100

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"
    - "RSS"
  page:
    - "HTML"
