params:
  # General
  title: "Gallery"
  description: "A uniquely styled Hugo photo gallery theme."
  author:
    name: "YourName"
    email: "user@example.com"
  defaultTheme: "auto" # Value: auto; light; dark;

  # .Param
  downImage:
    enable: true
    imageSpec: "fit 3200x3200"
  album:
    imageSpec:
      thumbnail: "fit 1200x1200"
  gallery:
    sort:
      - { key: "params.weight", order: "asc" }
      - { key: "params.date", order: "desc" }
      - { key: "title", order: "asc" }
      - { key: "name", order: "asc" }
    photoSwipe:
      enableCaption: true
      captionData:
        - { key: "Exif.ISO", value: "ISO %v" }
        - { key: "Exif.FocalLengthIn35mmFormat", value: "%v mm" }
        - { key: "Exif.ExposureCompensation", value: "%v ev" }
        - { key: "Exif.FNumber", value: "f %v" }
        - { key: "Exif.ExposureTime", value: "%v s" }
    justified:
      gutterH: 10
      gutterV: 10
      rowHeight: 320
      rowHeightTolerance: 0.25
    imageSpec:
      thumbnail: "fit 600x600"
      lightbox: "fit 1600x1600"
  watermark:
    path: "images/watermark/watermark.png" # assets/...
    opacity: 0.2
    size: 0.05
    x: 0.5
    y: 0.5

  # site.Params
  imageSpec:
    rssCover: "fill 900x600"
    featured: "fit 1600x1600"
    openGraph: "fit 1600x1600"
  socialIcons:
    github: "https://github.com/zero-dream/hugo-gallery/"
    facebook: "https://www.facebook.com/"
    youtube: "https://www.youtube.com/"
    email: "mailto:user@example.com"
    whatsapp: "1234567890"
