languages:
  en:
    disabled: false
    weight: 1
    label: English
    locale: "en-us"
    timeZone: "Etc/UTC"
  zh:
    disabled: true
    weight: 2
    label: 简体中文
    locale: "zh-cn"
    timeZone: "Asia/Shanghai"
